namespace hourOfAi.imgs {
    export const tiny_crick = img`a e e`;

    export const tiny_hopper = img`7 7 7`;

    export const tiny_bugsly = [
        img`
        . . e e e
        . e e b b
        8 8 8 8 8
        8 4 4 4 4
        `, img`
        . . . . .
        . e e e e
        8 8 8 8 8
        8 4 4 4 4
        `
    ];

    export const tiny_stinky = [
        img`
        . e e e . .
        e c c c e .
        e d d d d e
        . e e e e .
        `,
        img`
        . . . . . .
        . e e e e .
        e c c c d e
        . e e e e .
        `
    ]

    export const exclamation_point = img`
        . f f f f .
        f 2 2 2 2 f
        f 2 2 2 2 f
        f 2 2 2 2 f
        f 2 2 2 2 f
        . f 2 2 f .
        . . f f . .
        . f 2 2 f .
        . f 2 2 f .
        . . f f . .
    `;

    export const steam = [
        img`
            c .
            c c
            . c
        `,
        img`
            c c
            . c
            c .
        `,
        img`
            . c
            c .
            c c
        `
    ];

    export const small_shadow = [
        img`
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . 2 2 . 2 2 . . . . . .
            . . . . . . . 2 . 2 . . . . . . .
            . . . . . . 2 2 2 2 2 . . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . 2 2 2 2 2 2 2 . . . . .
            . . . . a d 2 2 2 2 2 d a . . . .
            . . . . a d d f f f d d a . . . .
            . . . a a a f f f f f a a a . . .
            . . . a a a f f f f f a a a . . .
            . . . a a a f f f f f a a a . . .
            . . . a a a f f f f f a a a . . .
        `,
        img`
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . 2 2 . 2 2 . . . . . .
            . . . . . . . 2 . 2 . . . . . . .
            . . . . . . 2 2 2 2 2 . . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . 2 2 2 2 2 2 2 . . . . .
            . . . . a d 2 2 2 2 2 d a . . . .
            . . . . a d d f f f d d a . . . .
            . . . . a a f f f f f a a . . . .
            . . . . a a f f f f f a a . . . .
            . . . . a a f f f f f a a . . . .
            . . . a a a f f f f f a a a . . .
            . . . . . . . . . . . . . . . . .
        `,
        img`
            . . . . . . 2 2 . 2 2 . . . . . .
            . . . . . . . 2 . 2 . . . . . . .
            . . . . . . 2 2 2 2 2 . . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . 2 2 2 2 2 2 2 . . . . .
            . . . . a d 2 2 2 2 2 d a . . . .
            . . . . a d d f f f d d a . . . .
            . . . . a a f f f f f a a . . . .
            . . . . a a f f f f f a a . . . .
            . . . . a a f f f f f a a . . . .
            . . . . a a f f f f f a a . . . .
            . . . . a . . . . . . . a . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
        `,
        img`
            . . . . . . . . . . . . . . . . .
            . . . . . . 2 2 . 2 2 . . . . . .
            . . . . . . . 2 . 2 . . . . . . .
            . . . . . . 2 2 2 2 2 . . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . 2 2 2 2 2 2 2 . . . . .
            . . . . a d 2 2 2 2 2 d a . . . .
            . . . a a d d f f f d d a a . . .
            . . . a a a f f f f f a a a . . .
            . . . a a a f f f f f a a a . . .
            . . . a a f f f f f f f a a . . .
            . . . a a f f f f f f f a a . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
        `,
        img`
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . 2 2 . 2 2 . . . . . .
            . . . . . . . 2 . 2 . . . . . . .
            . . . . . . 2 2 2 2 2 . . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . 2 2 2 2 2 2 2 . . . . .
            . . . . a d 2 2 2 2 2 d a . . . .
            . . . a a d d f f f d d a a . . .
            . . a a a a f f f f f a a a a . .
            . a a a a f f f f f f f a a a a .
            . a a a a f f f f f f f a a a a .
            . . a a f f f f f f f f f a . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
        `,
        img`
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . 2 2 . 2 2 . . . . . .
            . . . . . . . 2 . 2 . . . . . . .
            . . . . . . 2 2 2 2 2 . . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . 2 2 2 2 2 2 2 . . . . .
            . . . . a d 2 2 2 2 2 d a . . . .
            a a a a a d d f f f d d a a a a a
            a a a a a a f f f f f a a a a a a
            . a a a f f f f f f f f f a a a .
            . a a f f f f f f f f f f f a a .
            . . . . . . f f f f f . . . . . .
            . . . . . . . . . . . . . . . . .
        `,
        img`
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . 2 2 . 2 2 . . . . . .
            . . . . . . . 2 . 2 . . . . . . .
            . . . . . . 2 2 2 2 2 . . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . 2 2 2 2 2 2 2 . . . . .
            . . . . a d 2 2 2 2 2 d a . . . .
            . . . a a d d f f f d d a a . . .
            . . a a a a f f f f f a a a a . .
            . a a a a f f f f f f f a a a a .
            . a a a a f f f f f f f a a a a .
            . . a a f f f f f f f f f a . . .
            . . . . . . . . . . . . . . . . .
        `,
        img`
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . 2 2 . 2 2 . . . . . .
            . . . . . . . 2 . 2 . . . . . . .
            . . . . . . 2 2 2 2 2 . . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . 2 2 2 2 2 2 2 . . . . .
            . . . . a d 2 2 2 2 2 d a . . . .
            . . . . a d d f f f d d a . . . .
            . . . a a a f f f f f a a a . . .
            . . . a a a f f f f f a a a . . .
            . . . a a a f f f f f a a a . . .
            . . . a a a f f f f f a a a . . .
        `
    ];

    export const buttonFrame = img`
        . . e e e e e . .
        . e 2 2 2 2 2 e .
        e 2 2 2 2 2 2 2 f
        e 2 2 2 2 2 2 2 f
        e 2 2 2 2 2 2 2 f
        e 2 2 2 2 2 2 2 f
        e a 2 2 2 2 2 a f
        . f a a a a a f .
        . . f f f f f . .
    `;

    export const buttonFrameHover = img`
        . . e e e e e . .
        . e 8 8 8 8 8 e .
        e 8 8 8 8 8 8 8 f
        e 8 8 8 8 8 8 8 f
        e 8 8 8 8 8 8 8 f
        e 8 8 8 8 8 8 8 f
        e d 8 8 8 8 8 d f
        . f d d d d d f .
        . . f f f f f . .
    `;

    export const textFrame = img`
        . . e e e e e e e e e e e . .
        . e e b b b b b b b b b e e .
        e e b b c c c c c c c b b e e
        e b b c e e e e e e e c b c e
        e b c e f f f f f f f e b c e
        e b c e f f f f f f f e b c e
        e b c e f f f f f f f e b c e
        e b c e f f f f f f f e b c e
        e b c e f f f f f f f e b c e
        e b c e f f f f f f f e b c e
        e b c e f f f f f f f e b c e
        e b b c e e e e e e e b b c e
        e e b b b b b b b b b b c e e
        . e e c c c c c c c c c e e .
        . . e e e e e e e e e e e . .
    `;

    export const textFrameHover = img`
        . . e e e e e e e e e e e . .
        . e e b b b b b b b b b e e .
        e e b b c c c c c c c b b e e
        e b b c e e e e e e e c b c e
        e b c e a a a a a a a e b c e
        e b c e a a a a a a a e b c e
        e b c e a a a a a a a e b c e
        e b c e a a a a a a a e b c e
        e b c e a a a a a a a e b c e
        e b c e a a a a a a a e b c e
        e b c e a a a a a a a e b c e
        e b b c e e e e e e e b b c e
        e e b b b b b b b b b b c e e
        . e e c c c c c c c c c e e .
        . . e e e e e e e e e e e . .
    `;

    export const scrollbarDown = img`
        f f f f f f f f f
        f c c c c c c c f
        f c f f f f f c f
        f c f f f f f c f
        f c c f f f c c f
        f c c f f f c c f
        f c c c f c c c f
        f d d d d d d d f
        f f f f f f f f f
    `;

    export const scrollbarUp = img`
        f f f f f f f f f
        f c c c c c c c f
        f c c c f c c c f
        f c c f f f c c f
        f c c f f f c c f
        f c f f f f f c f
        f c f f f f f c f
        f d d d d d d d f
        f f f f f f f f f
    `;

    export const homeIcon = img`
        . . . . . a a . a . . .
        . . . . a 2 2 a c a . .
        . . . a 2 2 2 2 c a . .
        . . a 2 2 2 2 2 2 a . .
        . a 2 2 2 2 2 2 2 2 a .
        a 2 2 2 2 2 2 2 2 2 2 a
        . d b b b b b b b b d .
        . d b 9 b b b b 9 b d .
        . d b 9 b a a b 9 b d .
        . d b b b a 4 b b b d .
        . d b b b a a b b b d .
        . . d d d d d d d d . .
    `;

    export const homeIconHover = img`
        . . . . . . 4 4 . 4 . . . .
        . . . . . 4 a a 4 a 4 . . .
        . . . . 4 a 2 2 a c a 4 . .
        . . . 4 a 2 2 2 2 c a 4 . .
        . . 4 a 2 2 2 2 2 2 a 4 . .
        . 4 a 2 2 2 2 2 2 2 2 a 4 .
        4 a 2 2 2 2 2 2 2 2 2 2 a 4
        . 4 d b b b b b b b b d 4 .
        . 4 d b 9 b b b b 9 b d 4 .
        . 4 d b 9 b a a b 9 b d 4 .
        . 4 d b b b a 4 b b b d 4 .
        . 4 d b b b a a b b b d 4 .
        . . 4 d d d d d d d d 4 . .
        . . . 4 4 4 4 4 4 4 4 . . .
    `;

    export const padlock = img`
        .....fffffff.....
        ...ffdccccccff...
        ..fdccccccccccf..
        .fdccccfffdccccf.
        .fdcccf...fdcccf.
        .fdccf.....fdccf.
        .fdccf.....fdccf.
        .fdccf.....fdccf.
        .fdccf.....fdccf.
        .fdccf.....fdccf.
        .fdccf.....fdccf.
        fffffffffffffffff
        fedcccccccccccdef
        fedcccccccccccdef
        fedccccfffccccdef
        fedcccfffffcccdef
        fedcccfffffcccdef
        fedcccfffffcccdef
        fedccccfffccccdef
        fedccccfffccccdef
        fedcccccccccccdef
        fedcccccccccccdef
        fffffffffffffffff
    `;

    export const cloudLayer0 = img`
        bbbbbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbbbbbbbbbb....bbbbbbbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....bbbbb..bbbbbbbbbbbbbbbbbb......
        bbbbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....bbbbb..bbbbbbbbbbbbbbbbbb......bbbbbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...........bbbbbbbbbbbbbb..........
        bbbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...........bbbbbbbbbbbbbb.............bbbbbbbbb..bbbbbbbbbbbbbbbbbbbbbb.bbbbbbbbb............bbbb.bbbbbbbbb.........
        .bbbbbbbbb..bbbbbbbbbbbbbbbbbbbbbb.bbbbbbbbb............bbbb.bbbbbbbbb.............bbbbb.....bbbbbb.bbbbbbbbbbbbbbbb...bbbbb..................bbbbbbbbb.........
        ..bbbbb.....bbbbbb.bbbbbbbbbbbbbbbb...bbbbb..................bbbbbbbbb............bbbbb.......bbbb.bbbbbbbbbbbbbbbbbb..bbbbb................bbbbbb.bbb..........
        .bbbbb.......bbbb.bbbbbbbbbbbbbbbbbb..bbbbb................bbbbbb.bbb.............bbbbb...........bbbbbbbbbbbbbbbbbbb...bb..................bbbbbb..............
        .bbbbb...........bbbbbbbbbbbbbbbbbbb...bb..................bbbbbb..................bbb...........bbbbbbbbbbbbbbbbbbbb........................bbbb...............
        ..bbb...........bbbbbbbbbbbbbbbbbbbb........................bbbb.................................bbbbbbbbbbbbbbbbbbb............................................
        ................bbbbbbbbbbbbbbbbbbb...............................................................bbbbbbbbbbbbbbbb..............................................
        .................bbbbbbbbbbbbbbbb..................................................................bbbbbbbbb.bbbbb..............................................
        ..................bbbbbbbbb.bbbbb.....................................................................bbbbbb..bb................................................
        .....................bbbbbb..bb.......................................................................bbbbbb....................................................
        .....................bbbbbb............................................................................bbbb.....................................................
        ......................bbbb......................................................................................................................................
    `;

    export const cloudLayer1 = img`
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        ccccccccccccccc.cccccccc.cccccccccccccccccccccccccccccc.cccccccc.cccccccccccccccccccccccccccccc.cccccccc.cccccccccccccccccccccccccccccc.cccccccc.ccccccccccccccc
        c.cccccccccccc...cccccc.ccccccccccccccccc.cccccccccccc...cccccc.ccccccccccccccccc.cccccccccccc...cccccc.ccccccccccccccccc.cccccccccccc...cccccc.cccccccccccccccc
        c..cccccccccc......cc...ccccccccccccccccc..cccccccccc......cc...ccccccccccccccccc..cccccccccc......cc...ccccccccccccccccc..cccccccccc......cc...cccccccccccccccc
        c....cccccc............cccccccccccccccccc....cccccc............cccccccccccccccccc....cccccc............cccccccccccccccccc....cccccc............ccccccccccccccccc
        .......................ccccccccccc.ccccc.......................ccccccccccc.ccccc.......................ccccccccccc.ccccc.......................ccccccccccc.ccccc
        .......................ccccccccccc..ccc........................ccccccccccc..ccc........................ccccccccccc..ccc........................ccccccccccc..ccc.
        ........................ccccccccc...............................ccccccccc...............................ccccccccc...............................ccccccccc.......
        .........................ccccccc.................................ccccccc.................................ccccccc.................................ccccccc........
        ...........................ccc.....................................ccc.....................................ccc.....................................ccc..........
    `;

    export const cloudLayer2 = img`
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.ddddddddddddddddddddddddddddddddddd
        ddddddddddddddddddddddddddddddddddddddddddd.dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.dddddddddddddddddddddddddddddd...dd
        ddddddddddddddddddddddddddddddddddddddddddd.dddddddddddddddddddddddddddddd...ddddddddddddddddd.dddddddddddddddddddddddddddddd.ddddddddddddddddddddddddddddd....d
        ddddddddddddd.dddddddddddddddddddddddddddddd.ddddddddddddddddddddddddddddd....ddddddddddddddd.ddddddddddddddddddddddddddddddd....ddddd..dddddddddddddddddd......
        dddddddddddd.ddddddddddddddddddddddddddddddd....ddddd..dddddddddddddddddd......ddddddddddddd.dddddddddddddddddddddddddddddddd...........dddddddddddddd..........
        ddddddddddd.dddddddddddddddddddddddddddddddd...........dddddddddddddd.............ddddddddd..dddddddddddddddddddddd.ddddddddd............dddd.ddddddddd.........
        .ddddddddd..dddddddddddddddddddddd.ddddddddd............dddd.ddddddddd.............ddddd.....dddddd.dddddddddddddddd...ddddd..................ddddddddd.........
        ..ddddd.....dddddd.dddddddddddddddd...ddddd..................ddddddddd............ddddd.......dddd.dddddddddddddddddd..ddddd................dddddd.ddd..........
        .ddddd.......dddd.dddddddddddddddddd..ddddd................dddddd.ddd.............ddddd...........ddddddddddddddddddd...dd..................dddddd..............
        .ddddd...........ddddddddddddddddddd...dd..................dddddd..................ddd...........dddddddddddddddddddd........................dddd...............
        ..ddd...........dddddddddddddddddddd........................dddd.................................ddddddddddddddddddd............................................
        ................ddddddddddddddddddd...............................................................dddddddddddddddd..............................................
        .................dddddddddddddddd..................................................................ddddddddd.ddddd..............................................
        ..................ddddddddd.ddddd.....................................................................dddddd..dd................................................
        .....................dddddd..dd.......................................................................dddddd....................................................
        .....................dddddd............................................................................dddd.....................................................
        ......................dddd......................................................................................................................................
    `;

    export const cloudLayer3 = img`
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.ddddddddddddddddddddddddddddddddddd
        ddddddddddddddddddddddddddddddddddddddddddd.dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.dddddddddddddddddddddddddddddd...dd
        ddddddddddddddddddddddddddddddddddddddddddd.dddddddddddddddddddddddddddddd...ddddddddddddddddd.dddddddddddddddddddddddddddddd.ddddddddddddddddddddddddddddd....d
        ddddddddddddd.dddddddddddddddddddddddddddddd.ddddddddddddddddddddddddddddd....ddddddddddddddd.ddddddddddddddddddddddddddddddd....ddddd..dddddddddddddddddd......
        dddddddddddd.ddddddddddddddddddddddddddddddd....ddddd..dddddddddddddddddd......ddddddddddddd.dddddddddddddddddddddddddddddddd...........dddddddddddddd..........
        ddddddddddd.dddddddddddddddddddddddddddddddd...........dddddddddddddd.............ddddddddd..dddddddddddddddddddddd.ddddddddd............dddd.ddddddddd.........
        .ddddddddd..dddddddddddddddddddddd.ddddddddd............dddd.ddddddddd.............ddddd.....dddddd.dddddddddddddddd...ddddd..................ddddddddd.........
        ..ddddd.....dddddd.dddddddddddddddd...ddddd..................ddddddddd............ddddd.......dddd.dddddddddddddddddd..ddddd................dddddd.ddd..........
        .ddddd.......dddd.dddddddddddddddddd..ddddd................dddddd.ddd.............ddddd...........ddddddddddddddddddd...dd..................dddddd..............
        .ddddd...........ddddddddddddddddddd...dd..................dddddd..................ddd...........dddddddddddddddddddd........................dddd...............
        ..ddd...........dddddddddddddddddddd........................dddd.................................ddddddddddddddddddd............................................
        ................ddddddddddddddddddd...............................................................dddddddddddddddd..............................................
        .................dddddddddddddddd..................................................................ddddddddd.ddddd..............................................
        ..................ddddddddd.ddddd.....................................................................dddddd..dd................................................
        .....................dddddd..dd.......................................................................dddddd....................................................
        .....................dddddd............................................................................dddd.....................................................
        ......................dddd......................................................................................................................................
    `;

    export const lightningFrames = [
        img`
        ...........1....................
        ............1...................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        .................1..............
        ..................1.............
        ...................1............
        ....................1...........
        .....................1..........
        ......................1.........
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, img`
        ...........1....................
        ............1...................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        .................1..............
        ..................1.............
        ...................1............
        ....................1...........
        .....................1..........
        ......................1.........
        .......................1........
        ........................1.......
        ........................1.......
        .......................1........
        ......................1.........
        .....................1..........
        ....................1...........
        ...................1............
        ..................1.............
        .................1..............
        ................1...............
        ...............1................
        ..............1.................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, img`
        ...........1....................
        ............1...................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        .................1..............
        ..................1.............
        ...................1............
        ....................1...........
        .....................1..........
        ......................1.........
        .......................1........
        ........................1.......
        ........................1.......
        .......................1........
        ......................1.........
        .....................1..........
        ....................1...........
        ...................1............
        ..................1.............
        .................1..............
        ................1...............
        ...............1................
        ..............1.................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        ...............1.11.............
        ...............1...1............
        ...............1....1...........
        ..............1......1..........
        ..............1.......11........
        ..............1......1..1.......
        .............1.......1...1......
        .............1......1.....1.....
        ............1.......1...........
        ............1...................
        ...........1....................
        ...........1....................
        ..........1.....................
        ..........1.....................
        .........1......................
        ........1.......................
        ........1.......................
        .......1........................
        .......1........................
        ......1.........................
        ......1.........................
        .......1........................
        .......1........................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, img`
        ...........1....................
        ............1...................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        .................1..............
        ..................1.............
        ...................1............
        ....................1...........
        .....................1..........
        ......................1.........
        .......................1........
        ........................1.......
        ........................1.......
        .......................1........
        ......................1.........
        .....................1..........
        ....................1...........
        ...................1............
        ..................1.............
        .................1..............
        ................1...............
        ...............1................
        ..............1.................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        ...............1.11.............
        ...............1...1............
        ...............1....1...........
        ..............1......1..........
        ..............1.......11........
        ..............1......1..1.......
        .............1.......1...1......
        .............1......1.....1.....
        ............1.......1...........
        ............1...................
        ...........1....................
        ...........1....................
        ..........1.....................
        ..........1.....................
        .........1......................
        ........1.......................
        ........1.......................
        .......1........................
        .......1........................
        ......1.........................
        ......1.........................
        .......1........................
        .......1........................
        .......1........................
        ........1.......................
        ........1.......................
        .........1......................
        .........1......................
        .........1......................
        ..........1.....................
        ..........1.....................
        ..........1.....................
        ...........1....................
        ...........1....................
        ............1...................
        ............1...................
        ............1...................
        .............1..................
        .............1..................
        ..............1.................
        ..............1.................
        ..............1.................
        ...............1................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, img`
        ...........1....................
        ............1...................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        .................1..............
        ..................1.............
        ...................1............
        ....................1...........
        .....................1..........
        ......................1.........
        .......................1........
        ........................1.......
        ........................1.......
        .......................1........
        ......................1.........
        .....................1..........
        ....................1...........
        ...................1............
        ..................1.............
        .................1..............
        ................1...............
        ...............1................
        ..............1.................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        ...............1.11.............
        ...............1...1............
        ...............1....1...........
        ..............1......1..........
        ..............1.......11........
        ..............1......1..1.......
        .............1.......1...1......
        .............1......1.....1.....
        ............1.......1...........
        ............1...................
        ...........1....................
        ...........1....................
        ..........1.....................
        ..........1.....................
        .........1......................
        ........1.......................
        ........1.......................
        .......1........................
        .......1........................
        ......1.........................
        ......1.........................
        .......1........................
        .......1........................
        .......1........................
        ........1.......................
        ........1.......................
        .........1......................
        .........1......................
        .........1......................
        ..........1.....................
        ..........1.....................
        ..........1.....................
        ...........1....................
        ...........1....................
        ............1...................
        ............1...................
        ............1...................
        .............1..................
        .............1..................
        ..............1.................
        ..............1.................
        ..............1.................
        ...............1................
        ...............1................
        ...............1................
        ................1...............
        ................1...............
        .................1..............
        .................1..............
        .................1..............
        ..................1.............
        ..................1.............
        .................1.1............
        .................1.1............
        ................1...1...........
        ...............1.....1..........
        ..............1......1..........
        .............1........1.........
        .............1.........1........
        ............1..........1........
        ...........1............1.......
        `, img`
        ...........1....................
        ............1...................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        .................1..............
        ..................1.............
        ...................1............
        ....................1...........
        .....................1..........
        ......................1.........
        .......................1........
        ........................1.......
        ........................1.......
        .......................1........
        ......................1.........
        .....................1..........
        ....................1...........
        ...................1............
        ..................1.............
        .................1..............
        ................1...............
        ...............1................
        ..............1.................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        ...............1.11.............
        ...............1...1............
        ...............1....1...........
        ..............1......1..........
        ..............1.......11........
        ..............1......1..1.......
        .............1.......1...1......
        .............1......1.....1.....
        ............1.......1...........
        ............1...................
        ...........1....................
        ...........1....................
        ..........1.....................
        ..........1.....................
        .........1......................
        ........1.......................
        ........1.......................
        .......1........................
        .......1........................
        ......1.........................
        ......1.........................
        .......1........................
        .......1........................
        .......1........................
        ........1.......................
        ........1.......................
        .........1......................
        .........1......................
        .........1......................
        ..........1.....................
        ..........1.....................
        ..........1.....................
        ...........1....................
        ...........1....................
        ............1...................
        ............1...................
        ............1...................
        .............1..................
        .............1..................
        ..............1.................
        ..............1.................
        ..............1.................
        ...............1................
        ...............1................
        ...............1................
        ................1...............
        ................1...............
        .................1..............
        .................1..............
        .................1..............
        ..................1.............
        ..................1.............
        .................1.1............
        .................1.1............
        ................1...1...........
        ...............1.....1..........
        ..............1......1..........
        .............1........1.........
        .............1.........1........
        ............1..........1........
        ...........1............1.......
        `, img`
        ...........1.....111............
        ............1....1..............
        .............1..1...............
        ..............1.1...............
        ...............1................
        ..............111...............
        ..............1..1..............
        .............11...1.............
        .............1.....1............
        ............11......1...........
        ............1........1..........
        ...........11.........1.........
        ...........1...........1........
        ..........11............1.......
        .........11.............1.......
        .........11............1........
        ........11............1.........
        ........11...........1..........
        .......11...........1...........
        .......11..........1............
        .......11.........1.............
        .......11........1..............
        .......11.......1...............
        ........11.....1................
        ........11....1.................
        ........11...1..................
        .........11...1.................
        .........111...1................
        .........111....1...............
        ..........111..1.11.............
        ..........111..1...1............
        ...........11..1....1...........
        ...........1111......1..........
        ...........1111.......11........
        ............111......1..1.......
        ............111......1...1......
        ............111.....1.....1.....
        ............1111....1...........
        ............1111................
        ...........1.1111...............
        ...........1..111...............
        ..........1...111...............
        ..........1...1111..............
        .........1.....111..............
        ........1......1111.............
        ........1.......111.............
        .......1........1111............
        .......1.........111............
        ......1...........11............
        ......1............11...........
        .......1............1...........
        .......1............1...........
        .......1............11..........
        ........1...........11..........
        ........1...........11..........
        .........1.........111..........
        .........1.........111..........
        .........1........1111..........
        ..........1.......111...........
        ..........1.......111...........
        ..........1......111............
        ...........1.....111............
        ...........1....111.............
        ............1...111.............
        ............1..111..............
        ............1..111..............
        .............1111...............
        .............1111...............
        ..............11................
        .............111................
        .............11.................
        ............11.1................
        ............11.1................
        ...........111.1................
        ...........11...1...............
        ..........111...1...............
        ............1....1..............
        ............11...1..............
        ............11...1..............
        .............11...1.............
        .............11...1.............
        ..............11.1.1............
        ..............11.1.1............
        ..............111...1...........
        ...............11....1..........
        ..............1111...1..........
        .............1..11..1.1.........
        .............1..111..1.1........
        ............1.1..11..1.11.......
        ...........1...1.111...11.......
        `, img`
        .................bbb............
        .................b..............
        ................b...............
        ................b...............
        ...............b................
        ..............bb................
        ..............b.................
        .............bb.................
        .............b..................
        ............bb..................
        ............b...................
        ...........bb...................
        ...........b....................
        ..........bb....................
        .........bb.....................
        .........bb.....................
        ........bb......................
        ........bb......................
        .......bb.......................
        .......bb.......................
        .......bb.......................
        .......bb.......................
        .......bb.......................
        ........bb......................
        ........bb......................
        ........bb......................
        .........bb.....................
        .........bbb....................
        .........bbb....................
        ..........bbb...................
        ..........bbb...................
        ...........bb...................
        ...........bbb..................
        ...........bbb..................
        ............bbb.................
        ............bbb.................
        ............bbb.................
        ............bbbb................
        ............bbbb................
        .............bbbb...............
        ..............bbb...............
        ..............bbb...............
        ..............bbbb..............
        ...............bbb..............
        ...............bbbb.............
        ................bbb.............
        ................bbbb............
        .................bbb............
        ..................bb............
        ...................bb...........
        ....................b...........
        ....................b...........
        ....................bb..........
        ....................bb..........
        ....................bb..........
        ...................bbb..........
        ...................bbb..........
        ..................bbbb..........
        ..................bbb...........
        ..................bbb...........
        .................bbb............
        .................bbb............
        ................bbb.............
        ................bbb.............
        ...............bbb..............
        ...............bbb..............
        ..............bbb...............
        ..............bbb...............
        ..............bb................
        .............bbb................
        .............bb.................
        ............bb..................
        ............bb..................
        ...........bbb..................
        ...........bb...................
        ..........bbb...................
        ..........bbb...................
        ............bb..................
        ............bb..................
        .............bb.................
        .............bb.................
        ..............bb................
        ..............bb................
        ..............bbb...............
        ...............bb...............
        ...............bbb..............
        ..............bbbbbbb...........
        ............bbbbbbbbbbbb........
        ...........bbbbbbbbbbbbbb.......
        ...........bbbbbbbbbbbbbb.......
        `, img`
        .................bbb............
        .................b..............
        ................b...............
        ................b...............
        ...............b................
        ..............bb................
        ..............b.................
        .............bb.................
        .............b..................
        ............bb..................
        ............b...................
        ...........bb...................
        ...........b....................
        ..........bb....................
        .........bb.....................
        .........bb.....................
        ........bb......................
        ........bb......................
        .......bb.......................
        .......bb.......................
        .......bb.......................
        .......bb.......................
        .......bb.......................
        ........bb......................
        ........bb......................
        ........bb......................
        .........bb.....................
        .........bbb....................
        .........bbb....................
        ..........bbb...................
        ..........bbb...................
        ...........bb...................
        ...........bbb..................
        ...........bbb..................
        ............bbb.................
        ............bbb.................
        ............bbb.................
        ............bbbb................
        ............bbbb................
        .............bbbb...............
        ..............bbb...............
        ..............bbb...............
        ..............bbbb..............
        ...............bbb..............
        ...............bbbb.............
        ................bbb.............
        ................bbbb............
        .................bbb............
        ..................bb............
        ...................bb...........
        ....................b...........
        ....................b...........
        ....................bb..........
        ....................bb..........
        ....................bb..........
        ...................bbb..........
        ...................bbb..........
        ..................bbbb..........
        ..................bbb...........
        ..................bbb...........
        .................bbb............
        .................bbb............
        ................bbb.............
        ................bbb.............
        ...............bbb..............
        ...............bbb..............
        ..............bbb...............
        ..............bbb...............
        ..............bb................
        .............bbb................
        .............bb.................
        ............bb..................
        ............bb..................
        ...........bbb..................
        ...........bb...................
        ..........bbb...................
        ...........bb...................
        ............bb..................
        ............bb..................
        .............bb.................
        .............bb.....b...........
        ..............bb....bb..........
        ..............bb..bbbbbb........
        .........bb.bbbbbbbbbbbb........
        .........bbbbbbbbbbbbbbb........
        ..........bbbbbbbbbbbbbbbbb.....
        ...........bbbbbbbbbbbbbbbb.....
        .........bbbbbbbbbbbbbbbbb......
        .........bbbbbbbbbbbbbbbb.......
        ..........bbbbbbbbbbbbbbb.b.....
        `, img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        .......b........................
        ......b.........................
        ......b.........................
        .......b........................
        .......b........................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ..................bb............
        ...................bb...........
        ....................b...........
        ....................b...........
        ....................b...........
        ....................b...........
        ....................b...........
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ............bb..................
        ...........bbb..................
        ...........b....................
        ..........bb....................
        ..........bb....................
        ...........b....................
        ............b...................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ..........................b.....
        `, img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        .......b........................
        ................................
        ....b...........................
        ................................
        ....b...........................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ....................b...........
        .....................b..........
        ................................
        ......................b.........
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ..........b.....................
        .........b......................
        ................................
        ................................
        ................................
        .........b......................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ..........................b.....
        `
    ];

    export const tower_section_no_window = img`
.fff............................................................fff.
fefdf..........................................................fdfef
feffdf........................................................fdffef
fefefcf......................................................fcfefef
.ffeffcff..................................................ffcffeff.
..fefdffcff..............................................ffcffdfef..
..fffdfdffcffff......................................ffffcffdfdfff..
..fffdfdfdffcfcffff..............................ffffcfcffdfdfdfff..
..fffffdfdfdffffcfcffffff..................ffffffcfcffffdfdfdfffff..
..fefefffdfdfdffffffcfcfcffffffffffffffffffccfccffffffcfdfdfffefef..
..fefeeffffdfdfcfcffffffffccfccfccfccfccfccfffffffcfcfcfdffffeefef..
..fefdefeefffdfcfcfcfcfccfffffffffffffffffffccfccfcfcfcfffeefedfef..
..fefddfeeeefffcfcfcfcfccfccfccfccfccfccfccfccfccfcfcfffeeeefddfef..
..fefddfddeeefdffffcfcfccfccfccfccfccfccfccfccfccffffddfeeddfddfef..
..fffddfddddefdddddfffffffccfccfccfccfccfccffffffddddddfddddfddfff..
..fefddfdddddfcdddddfddddffffffffffffffffffddddfdddddccfddddfddfef..
..feefdfdddddfccccccfddddddddfdddddddddfdddddddfdccccccfddddfdfeef..
..feefffdddddfccccccfccccddddfdddddddddfdddccccfcccccccfddddfffeef..
..feefddffdddfccccccfccccccccfcccccccccfcccccccfcccccccfddffddfeef..
..feefdddfffdfccccccfccccccccfcccccccccfcccccccfcccccccffffdddfeef..
..feefdddfddfffcccccfccccccccfcccccccccfcccccccfcccccfffddfdddfeef..
..feefdddfdddddffffcfccccccccfcccccccccfcccccccfcffffdddddfdddfeef..
..ffefdddfdddddfcccffffffccccfcccccccccfcccffffffcccfdddddfdddfeff..
..feffdddfdddddfcccccccfcfffffffffffffffffffccccccccfdddddfdddffef..
..feffdddfdddddfcccccccfcccccccccfcccccccccfccccccccfdddddfdddffef..
..fefdffdfdddddfcccccccfcccccccccfcccccccccfccccccccfdddddfdffdfef..
..fefddfffdddddfcccccccfcccccccccfcccccccccfccccccccfdddddfffddfef..
..fefddfddffdddfcccccccfcccccccccfcccccccccfccccccccfdddffddfddfef..
..fefddfddddffffcccccccfcccccccccfcccccccccfccccccccffffddddfddfef..
..fefddfdddddfcffffccccfcccccccccfcccccccccfcccccffffccfddddfddfef..
..fffddfdddddfcccccffffffccccccccfcccccccccffffffccccccfddddfddfff..
..fefddfdddddfccccccfccccffffffffffffffffffccccfcccccccfddddfddfef..
..feefdfdddddfccccccfcccccccccfcccccccfccccccccfcccccccfddddfdfeef..
..feefffdddddfccccccfcccccccccfcccccccfccccccccfcccccccfddddfffeef..
..feefddffdddfccccccfcccccccccfcccccccfccccccccfcccccccfddffddfeef..
..feefdddfffdfccccccfcccccccccfcccccccfccccccccfcccccccffffdddfeef..
..feefdddfddfffcccccfcccccccccfcccccccfccccccccfcccccfffddfdddfeef..
..feefdddfdddddffffcfcccccccccfcccccccfccccccccfcffffdddddfdddfeef..
..ffefdddfdddddfcccffffffcccccfcccccccfccccffffffcccfdddddfdddfeff..
..feffdddfdddddfcccccccfcfffffffffffffffffffccccccccfdddddfdddffef..
..feffdddfdddddfcccccccfccccccccccfccccccccfccccccccfdddddfdddffef..
..fefdffdfdddddfcccccccfccccccccccfccccccccfccccccccfdddddfdffdfef..
..fefddfffdddddfcccccccfccccccccccfccccccccfccccccccfdddddfffddfef..
..fefddfddffdddfcccccccfccccccccccfccccccccfccccccccfdddffddfddfef..
..fefddfddddffffcccccccfccccccccccfccccccccfccccccccffffddddfddfef..
..fefddfdddddfcffffccccfccccccccccfccccccccfcccccffffccfddddfddfef..
..fffddfdddddfcccccfffffccccccccccfccccccccffffffccccccfddddfddfff..
..fefddfdddddfccccccfcccfffffffffffffffffffccccfcccccccfddddfddfef..
..feefdfdddddfccccccfccccccccfcccccccccfcccccccfcccccccfddddfdfeef..
..feefffdddddfccccccfccccccccfcccccccccfcccccccfcccccccfddddfffeef..
..feefddffdddfccccccfccccccccfcccccccccfcccccccfcccccccfddffddfeef..
..feefdddfffdfccccccfccccccccfcccccccccfcccccccfcccccccffffdddfeef..
..feefdddfddfffcccccfccccccccfcccccccccfcccccccfcccccfffddfdddfeef..
..feefdddfdddddffffcfccccccccfcccccccccfcccccccfcffffdddddfdddfeef..
...fefdddfdddddfcccffffffccccfcccccccccfcccffffffcccfdddddfdddfef...
....ffdddfdddddfcccccccfcfffffffffffffffffffccccccccfdddddfdddff....
.....fdddfdddddfcccccccfcccccccccfcccccccccfccccccccfdddddfdddf.....
......ffdfdddddfcccccccfcccccccccfcccccccccfccccccccfdddddfdff......
........ffdddddfcccccccfcccccccccfcccccccccfccccccccfdddddff........
..........ffdddfcccccccfcccccccccfcccccccccfccccccccfdddff..........
............ffffcccccccfcccccccccfcccccccccfccccccccffff............
...............ffffccccfcccccccccfcccccccccfcccccffff...............
...................ffffffccccccccfcccccccccffffff...................
.........................ffffffffffffffffff.........................
`;

    export const hot_air_balloon = img`
        .........................ddddddddddddddddd.........................
        .....................dddd88888888888888888dddd.....................
        ...................dd55d8888888888888888888d22dd...................
        .................dd5555ddd888888888888888ddd2222dd.................
        ...............dd555ddd555ddddddddddddddd222ddd222dd...............
        ..............d555dd55555d555d55d5d22d222d22222dd222d..............
        .............d55dd55555dd555d22d222d22d222dd22222dd22d.............
        ...........dd55d55555dd222dd222d222d222dd222dd22222d88dd...........
        ..........d555d55555d2222d2222d22222d2222d2222d22222d888d..........
        .........d5555d2222d2222d22222d22222d22222d2222d8888d8888d.........
        ........d5555d222dd2222d22222d2222222d22222d2222dd888d8888d........
        .......d2222d222d22222d222222d2222222d222222d88888d888d8888d.......
        .......d2222d22d222222d22222d222222222d22222d888888d88d8888d.......
        ......d222dd222d22222d222222d222222222d888888d88888d888dd888d......
        .....d222d2222d222222d222222d222222222d888888d888888d8888d888d.....
        ....d2222d2222d222222d222222d888888888d888888d888888d8888d8888d....
        ....d222d2222d222222d8888888d888888888d8888888d888888d8888d888d....
        ...d222d22222d222222d888888d88888888888d888888d888888d88888d555d...
        ...d222d22222d888888d888888d88888888888d888888d888888d88888d555d...
        ..d222d22222d8888888d888888d88888888888d888888d8888888d55555d555d..
        ..d22d888888d888888d8888888d88888888888d8888888d888888d555555d55d..
        .d222d888888d888888d8888888d88888888888d8888888d555555d555555d555d.
        .d888d888888d888888d8888888d88888888888d8888888d555555d555555d555d.
        .d888d88888d8888888d8888888d88888888888d5555555d5555555d55555d555d.
        .d88d888888d8888888d8888888d88888888888d5555555d5555555d555555d55d.
        d888d888888d8888888d8888888d55555555555d5555555d5555555d555555d555d
        d888d888888d8888888d8888888d55555555555d5555555d5555555d555555d555d
        d888d888888d8888888d5555555d55555555555d5555555d5555555d555555d222d
        d888d888888d8888888d5555555d55555555555d5555555d5555555d555555d222d
        d888d888888d5555555d5555555d55555555555d5555555d5555555d225552d222d
        d888d888888d5555555d5555555d55555555555d5555555d5555555d222222d222d
        d888d555555d5555555d5555555d55555555555d5555555d2222222d222222d222d
        d888d555555d5555555d5555555d55555555555d5555555d2222222d222222d222d
        d555d555555d5555555d5555555d55555555555d2222222d2222222d222222d222d
        .d55d555555d5555555d5555555d55555555555d2222222d2222222d222222d88d.
        .d555d55555d5555555d5555555d22222222222d2222222d2222222d22222d888d.
        .d555d555555d5555555d555555d22222222222d222222d2222222d888888d888d.
        .d5555d55555d5555555d2222222d222222222d2222222d2222222d88888d8888d.
        ..d5555d55555d555555d2222222d222222222d2222222d888888d88888d8888d..
        ..d5555d55555d222222d2222222d222222222d2222222d888888d88888d8888d..
        ...d5555d5555d222222d2222222d222222222d8888888d888888d8888d5555d...
        ...d55555d2222d22222d22222222d2222222d88888888d88888d8888d55555d...
        ....d5555d2222d222222d2222222d8888888d8888888d888888d5555d5555d....
        ....d22222d2222d22222d2222222d8888888d8888888d88888d5555d55555d....
        .....d22222d222d22222d8888888d8888888d8888888d55555d555d55555d.....
        ......d2222d2222d22222d888888d8888888d888888d55555d5555d5555d......
        .......d2222d222d88888d888888d8888888d555555d55555d555d2222d.......
        .......d2222d2222d88888d88888d8888888d55555d55555d5555d2222d.......
        ........d2222d888d88888d888888d55555d555555d55555d222d2222d........
        ........d22222d888d88888d88888d55555d55555d55555d222d22222d........
        .........d8888d8888d8888d55555d55555d55555d2222d2222d2222d.........
        ..........d8888d888d88888d5555d55555d5555d22222d222d8888d..........
        ...........d8888d888d5555d5555d55555d2222d2222d222d8888d...........
        ...........d8888d8888d555d5555d55555d2222d222d8888d8888d...........
        ............d8888d555d5555d555d22222d222d2222d888d8888d............
        .............d8888d555d555d555d22222d222d888d888d8888d.............
        ..............d555d555d5555d222d222d222d8888d888d888d..............
        ..............d5555d555d555d222d222d888d888d888d5555d..............
        ...............d5555d555d222d22d222d88d888d888d5555d...............
        ................d555d555d222d22d888d88d888d555d555d................
        .................d555d222d222d88d8d88d888d555d555d.................
        ..................d55d222d222d88d8d88d555d555d55d..................
        ..................d222d222d888d8d8d8d555d555d555d..................
        ...................d222d222d88d8d5d5d55d555d555d...................
        ....................d22d888d88d55d55d55d555d55d....................
        .....................d22d888d55d5d5d55d555d22d.....................
        .....................d888d888d5d5d5d5d552d222d.....................
        ......................d88d855d55d5d55d222d22d......................
        .......................d88d555d5d5d5d222d22d.......................
        ........................d55d55d5d5d2d22d22d........................
        ........................d55d555d222d222d22d........................
        .........................d55d55d222d22d22d.........................
        ..........................dddd2d222d2dddd..........................
        ..........................e868ddddddd868e..........................
        ..........................e8686868686868e..........................
        ...........................e68686868686e...........................
        ...........................edd6868686dde...........................
        ............................eddddddddde............................
        ............................edeeeeeeede............................
        ............................ede.....ede............................
        ............................edeedddeede............................
        ............................eddcccccdde............................
        ............................edeeccceede............................
        ............................ede.eee.ede............................
        ............................ede.....ede............................
        ............................ede.....ede............................
        ............................ede.....ede............................
        ............................ede.....ede............................
        ............................edeeeeeeede............................
        ...........................e4a4a4a4a4a4e...........................
        ..........................e3334333433343e..........................
        ..........................ea4a4a4a4a4a4ae..........................
        ..........................e3433343334333e..........................
        ..........................ea4a4a4a4a4a4ae..........................
        ..........................e3334333433343e..........................
        ..........................ea4a4a4a4a4a4ae..........................
        ..........................e3433343334333e..........................
        ..........................ea4a4a4a4a4a4ae..........................
        ...........................e33433343334e...........................
        ............................eeeeeeeeeee............................
    `

    export const clouds = [
        img`
............................11.....................
.........................1111111...................
........................111111111111...............
.......................11111111111111..............
......................1111111111111111.............
.....................11111111111111111.............
..................111111111111111111111............
...............1111111111111111111111111...........
..........1111111111111111111111111111111..........
.........111111111111111111111111111111111.........
........111111111111111111111111111111111111.......
.......111111111111111111111111111111111111111.....
.......1111111111111111111111111111111111111111....
.......11111111111111111111111111111111111111111...
.......111111111111111111111111111111111111111111..
......1111111111111111111111111111111111111111111..
....111111111111111111111111111111111111111111111..
...11111111111111111111111111111111111111111111111.
..111111111111111111111111111111111111111111111111.
.11111111111111111111111111111111111111111111111111
111111111111111111111111111111111111111111111111111
11111111111111111111111111111111111111111111111111.
.....1111111111111111111111111111111111111111......
`,
        img`
.........................11111................
........................1111111...............
......................1111111111..............
..................111111111111111.............
...............111111111111111111.............
..............1111111111111111111111111.......
.............111111111111111111111111111......
.............111111111111111111111111111......
.............1111111111111111111111111111.....
............11111111111111111111111111111.....
............111111111111111111111111111111....
............111111111111111111111111111111....
...........11111111111111111111111111111111...
......11111111111111111111111111111111111111..
.....1111111111111111111111111111111111111111.
....11111111111111111111111111111111111111111.
...1111111111111111111111111111111111111111111
...1111111111111111111111111111111111111111111
...1111111111111111111111111111111111111111111
...1111111111111111111111111111111111111111111
..11111111111111111111111111111111111111111111
.111111111111111111111111111111111111111111111
111111111111111111111111111111111111111111111.
11111111111111111..................111111111..
`,
        img`
........11111111.................
.......1111111111................
....11111111111111...............
...1111111111111111..............
..11111111111111111111111........
..111111111111111111111111.......
.11111111111111111111111111......
.111111111111111111111111111.....
1111111111111111111111111111.....
111111111111111111111111111111...
.111111111111111111111111111111..
.1111111111111111111111111111111.
..1111111111111111111111111111111
.....1111111111111111111111111111
......111111111111111111111111...
.................................
`,
        img`
...................1111................................................
..................111111...............................................
.................11111111111111........................................
................1111111111111111.......................................
..............1111111111111111111......................................
............1111111111111111111111.....................................
...........11111111111111111111111.....................................
..........111111111111111111111111.....................................
..........1111111111111111111111111......11111.........................
.........11111111111111111111111111...111111111........................
.........111111111111111111111111111111111111111.......................
.......111111111111111111111111111111111111111111......................
......1111111111111111111111111111111111111111111111...................
....11111111111111111111111111111111111111111111111111.................
...1111111111111111111111111111111111111111111111111111................
...11111111111111111111111111111111111111111111111111111...............
..1111111111111111111111111111111111111111111111111111111..............
..1111111111111111111111111111111111111111111111111111111..............
..11111111111111111111111111111111111111111111111111111111.............
..111111111111111111111111111111111111111111111111111111111............
..11111111111111111111111111111111111111111111111111111111111..........
..1111111111111111111111111111111111111111111111111111111111111........
..111111111111111111111111111111111111111111111111111111111111111111...
.11111111111111111111111111111111111111111111111111111111111111111111..
1111111111111111111111111111111111111111111111111111111111111111111111.
1111111111111111111111111111111111111111111111111111111111111111111111.
11111111111111111111111111111111111111111111111111111111111111111111111
.1111111111111111111111111111111111111111111111111111111111111111111111
..11111111111111111111111111111111111111111111111111111111111111111111.
...............1111111111111111111111111111111..........11111111.......
`,
        img`
........................1111...........
.................1111..111111..........
...............111111111111111.........
.............111111111111111111........
............11111111111111111111.......
.........111111111111111111111111......
........1111111111111111111111111......
.......1111111111111111111111111111....
......111111111111111111111111111111...
.....11111111111111111111111111111111..
.....111111111111111111111111111111111.
....1111111111111111111111111111111111.
....11111111111111111111111111111111111
....11111111111111111111111111111111111
..1111111111111111111111111111111111111
.1111111111111111111111111111111111111.
1111111111111111111111111111111111111..
111111111111111111.....................
`
    ]

    export const bird_frames = [
    img`
        . . . . . e e e e . . .
        . . . . e 1 1 1 1 e . .
        . . . e 1 1 1 1 e . . .
        . . . e 1 1 1 e . . . .
        . . . e 1 1 1 e . . . .
        . . e e 1 1 1 e . . . .
        . e 4 1 1 1 1 1 e . . .
        . . e e e e e e . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        `,
    img`
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . e e e e e e . .
        . . . e 1 1 1 1 1 1 e .
        . . e 1 1 1 1 1 e e . .
        . . e 1 1 1 1 e . . . .
        . e 4 1 1 1 1 1 e . . .
        . . e e e e e e . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        `,
    img`
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . e e e e . . . . .
        . . e 1 1 1 1 e . . . .
        . e 4 1 1 1 1 1 e e e .
        . . e 1 1 1 1 1 1 1 1 e
        . . . e e e e e e e e .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        `,
    img`
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . e e e e e e . . . .
        . e 4 1 1 1 1 1 e . . .
        . . e 1 1 1 1 e e . . .
        . . e 1 1 1 1 1 1 e e .
        . . . e 1 1 1 1 1 1 1 e
        . . . . e e e e e e e .
        . . . . . . . . . . . .
        `,
    img`
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . e e e e e e . . . .
        . e 4 1 1 1 1 1 e . . .
        . . e 1 1 1 1 e . . . .
        . . e 1 1 1 1 e e . . .
        . . . e 1 1 1 1 1 e . .
        . . . . e 1 1 1 1 1 e .
        . . . . . e e e e e . .
        `,
    img`
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . e e e e e e . . . .
        . e 4 1 1 1 1 1 e . . .
        . . e 1 1 1 1 e . . . .
        . . e 1 1 1 1 e e . . .
        . . . e 1 1 1 1 1 e . .
        . . . . e 1 1 1 1 1 e .
        . . . . . e e e e e . .
        `,
    img`
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . e e e e e e . . . .
        . e 4 1 1 1 1 1 e . . .
        . . e 1 1 1 1 e e . . .
        . . e 1 1 1 1 1 1 e e .
        . . . e 1 1 1 1 1 1 1 e
        . . . . e e e e e e e .
        . . . . . . . . . . . .
        `,
    img`
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . e e e e . . . . .
        . . e 1 1 1 1 e . . . .
        . e 4 1 1 1 1 1 e e e .
        . . e 1 1 1 1 1 1 1 1 e
        . . . e e e e e e e e .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        `,
    img`
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . e e e e e e . .
        . . . e 1 1 1 1 1 1 e .
        . . e 1 1 1 1 1 e e . .
        . . e 1 1 1 1 e . . . .
        . e 4 1 1 1 1 1 e . . .
        . . e e e e e e . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        `,
    img`
        . . . . . e e e e . . .
        . . . . e 1 1 1 1 e . .
        . . . e 1 1 1 1 e . . .
        . . . e 1 1 1 e . . . .
        . . . e 1 1 1 e . . . .
        . . e e 1 1 1 e . . . .
        . e 4 1 1 1 1 1 e . . .
        . . e e e e e e . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        . . . . . . . . . . . .
        `
    ];

    export const infinity_icon = img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ......fffff..........fffff......
        ....ff22222ff......ffaaaaaff....
        ...f222222222f....faafffffaaf...
        ..f22222222222f..faff.....faaf..
        .f2222fffff2222ffaf........faaf.
        .f222f.....ff222af..........faf.
        f222f.......f222af..........faaf
        fa22f........f222f...........faf
        faa2f.........f222f..........f2f
        faaaf........fa222f.........f22f
        .faaaf.......faf222f.......f22f.
        .faaaf......faaff222f......f22f.
        ..faaaff..ffaaf..f222ffffff22f..
        ...faaaaffaaaf....f222222222f...
        ....ffaaaaaff......ff22222ff....
        ......fffff..........fffff......
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
    `;

    export const stopwatch_icon = img`
        ................................
        ..............fffff.............
        ..............faaaf.............
        ...............faf..............
        ...........fffffffffff..........
        .........ffaaaaaaaaaaaff........
        ........faaafffffffffaaaf.......
        .......faaff111111111ffaaf......
        ......faaf111111f111111faaf.....
        .....faaf11c111fcf111c11faaf....
        ....faaf1111c11fcf11c1111faaf...
        ....faf11111111fcf11111111faf...
        ...faaf1c111111fcf111111c1faaf..
        ...faf111c11111fcf11111c111faf..
        ...faf111111111fcf111111111faf..
        ...faf111111111fcf111111111faf..
        ...faf11111111fdddffff11111faf..
        ...faf1dd11111fdadccccf1dd1faf..
        ...faf11111111fdddffff11111faf..
        ...faf111111111fff111111111faf..
        ...faf111111111111111111111faf..
        ...faf111c1111111111111c111faf..
        ...faaf1c111111111111111c1faaf..
        ....faf1111111111111111111faf...
        ....faaf1111c1111111c1111faaf...
        .....faaf11c1111d1111c11faaf....
        ......faaf111111d111111faaf.....
        .......faaff111111111ffaaf......
        ........faaafffffffffaaaf.......
        .........ffaaaaaaaaaaaff........
        ...........fffffffffff..........
        ................................
    `;

    export const continue_icon = img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ....................ff..........
        ...................f77f.........
        ...................f777f........
        ...................f7777f.......
        ...................f77777f......
        ..ffffffffffffffffff777777f.....
        .f7777777777777777777777777f....
        .f77777777777777777777777777f...
        .f777777777777777777777777777f..
        .f7777777777777777777777777777f.
        .f777777777777777777777777777f..
        .f77777777777777777777777777f...
        .f7777777777777777777777777f....
        ..ffffffffffffffffff777777f.....
        ...................f77777f......
        ...................f7777f.......
        ...................f777f........
        ...................f77f.........
        ....................ff..........
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
    `;

    export const restart_icon = img`
        ................................
        ................................
        ............ffffffffff..........
        ...f......ff2222222222ff........
        ..f2f....f22222222222222ff......
        ..f22f..f22222222222222222f.....
        ..f222ff2222222222222222222f....
        ..f2222222222222222222222222f...
        ..f22222222222222222222222222f..
        ..f22222222222222222222222222f..
        ..f22222222222ffffff222222222f..
        ..f2222222222f......f222222222f.
        ..f222222222f........f22222222f.
        ..f2222222222f........f2222222f.
        ..f22222222222f.......f2222222f.
        ..f222222222222f......f2222222f.
        ..f2222222222222f.....f2222222f.
        ...fffffffffffff......f2222222f.
        ......................f2222222f.
        ......................f2222222f.
        ..........f..........f22222222f.
        .........f2f........f222222222f.
        ........f222ffffffff222222222f..
        .......f222222222222222222222f..
        ......f222222222222222222222f...
        .....f2222222222222222222222f...
        .....f222222222222222222222f....
        ......f2222222222222222222f.....
        .......ff222222222222222ff......
        .........ff22222222222ff........
        ...........fffffffffff..........
        ................................
    `;
}