namespace hourOfAi.imgs {
    export const tiny_crick = img`a e e`;

    export const tiny_hopper = img`7 7 7`;

    export const tiny_bugsly = [
        img`
        . . e e e
        . e e b b
        8 8 8 8 8
        8 4 4 4 4
        `, img`
        . . . . .
        . e e e e
        8 8 8 8 8
        8 4 4 4 4
        `
    ];

    export const steam = [
        img`
            c .
            c c
            . c
        `,
        img`
            c c
            . c
            c .
        `,
        img`
            . c
            c .
            c c
        `
    ];

    export const small_shadow = [
        img`
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . 2 2 . 2 2 . . . . . .
            . . . . . . . 2 . 2 . . . . . . .
            . . . . . . 2 2 2 2 2 . . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . 2 2 2 2 2 2 2 . . . . .
            . . . . a d 2 2 2 2 2 d a . . . .
            . . . . a d d f f f d d a . . . .
            . . . a a a f f f f f a a a . . .
            . . . a a a f f f f f a a a . . .
            . . . a a a f f f f f a a a . . .
            . . . a a a f f f f f a a a . . .
        `,
        img`
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . 2 2 . 2 2 . . . . . .
            . . . . . . . 2 . 2 . . . . . . .
            . . . . . . 2 2 2 2 2 . . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . 2 2 2 2 2 2 2 . . . . .
            . . . . a d 2 2 2 2 2 d a . . . .
            . . . . a d d f f f d d a . . . .
            . . . . a a f f f f f a a . . . .
            . . . . a a f f f f f a a . . . .
            . . . . a a f f f f f a a . . . .
            . . . a a a f f f f f a a a . . .
            . . . . . . . . . . . . . . . . .
        `,
        img`
            . . . . . . 2 2 . 2 2 . . . . . .
            . . . . . . . 2 . 2 . . . . . . .
            . . . . . . 2 2 2 2 2 . . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . 2 2 2 2 2 2 2 . . . . .
            . . . . a d 2 2 2 2 2 d a . . . .
            . . . . a d d f f f d d a . . . .
            . . . . a a f f f f f a a . . . .
            . . . . a a f f f f f a a . . . .
            . . . . a a f f f f f a a . . . .
            . . . . a a f f f f f a a . . . .
            . . . . a . . . . . . . a . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
        `,
        img`
            . . . . . . . . . . . . . . . . .
            . . . . . . 2 2 . 2 2 . . . . . .
            . . . . . . . 2 . 2 . . . . . . .
            . . . . . . 2 2 2 2 2 . . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . 2 2 2 2 2 2 2 . . . . .
            . . . . a d 2 2 2 2 2 d a . . . .
            . . . a a d d f f f d d a a . . .
            . . . a a a f f f f f a a a . . .
            . . . a a a f f f f f a a a . . .
            . . . a a f f f f f f f a a . . .
            . . . a a f f f f f f f a a . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
        `,
        img`
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . 2 2 . 2 2 . . . . . .
            . . . . . . . 2 . 2 . . . . . . .
            . . . . . . 2 2 2 2 2 . . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . 2 2 2 2 2 2 2 . . . . .
            . . . . a d 2 2 2 2 2 d a . . . .
            . . . a a d d f f f d d a a . . .
            . . a a a a f f f f f a a a a . .
            . a a a a f f f f f f f a a a a .
            . a a a a f f f f f f f a a a a .
            . . a a f f f f f f f f f a . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
        `,
        img`
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . 2 2 . 2 2 . . . . . .
            . . . . . . . 2 . 2 . . . . . . .
            . . . . . . 2 2 2 2 2 . . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . 2 2 2 2 2 2 2 . . . . .
            . . . . a d 2 2 2 2 2 d a . . . .
            a a a a a d d f f f d d a a a a a
            a a a a a a f f f f f a a a a a a
            . a a a f f f f f f f f f a a a .
            . a a f f f f f f f f f f f a a .
            . . . . . . f f f f f . . . . . .
            . . . . . . . . . . . . . . . . .
        `,
        img`
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . 2 2 . 2 2 . . . . . .
            . . . . . . . 2 . 2 . . . . . . .
            . . . . . . 2 2 2 2 2 . . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . 2 2 2 2 2 2 2 . . . . .
            . . . . a d 2 2 2 2 2 d a . . . .
            . . . a a d d f f f d d a a . . .
            . . a a a a f f f f f a a a a . .
            . a a a a f f f f f f f a a a a .
            . a a a a f f f f f f f a a a a .
            . . a a f f f f f f f f f a . . .
            . . . . . . . . . . . . . . . . .
        `,
        img`
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . . .
            . . . . . . 2 2 . 2 2 . . . . . .
            . . . . . . . 2 . 2 . . . . . . .
            . . . . . . 2 2 2 2 2 . . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . f f 2 2 2 f f . . . . .
            . . . . . 2 2 2 2 2 2 2 . . . . .
            . . . . a d 2 2 2 2 2 d a . . . .
            . . . . a d d f f f d d a . . . .
            . . . a a a f f f f f a a a . . .
            . . . a a a f f f f f a a a . . .
            . . . a a a f f f f f a a a . . .
            . . . a a a f f f f f a a a . . .
        `
    ];

    export const buttonFrame = img`
        . . e e e e e . .
        . e 2 2 2 2 2 e .
        e 2 2 2 2 2 2 2 f
        e 2 2 2 2 2 2 2 f
        e 2 2 2 2 2 2 2 f
        e 2 2 2 2 2 2 2 f
        e a 2 2 2 2 2 a f
        . f a a a a a f .
        . . f f f f f . .
    `;

    export const buttonFrameHover = img`
        . . e e e e e . .
        . e 8 8 8 8 8 e .
        e 8 8 8 8 8 8 8 f
        e 8 8 8 8 8 8 8 f
        e 8 8 8 8 8 8 8 f
        e 8 8 8 8 8 8 8 f
        e d 8 8 8 8 8 d f
        . f d d d d d f .
        . . f f f f f . .
    `;

    export const textFrame = img`
        . . e e e e e e e e e e e . .
        . e e b b b b b b b b b e e .
        e e b b c c c c c c c b b e e
        e b b c e e e e e e e c b c e
        e b c e f f f f f f f e b c e
        e b c e f f f f f f f e b c e
        e b c e f f f f f f f e b c e
        e b c e f f f f f f f e b c e
        e b c e f f f f f f f e b c e
        e b c e f f f f f f f e b c e
        e b c e f f f f f f f e b c e
        e b b c e e e e e e e b b c e
        e e b b b b b b b b b b c e e
        . e e c c c c c c c c c e e .
        . . e e e e e e e e e e e . .
    `;

    export const textFrameHover = img`
        . . e e e e e e e e e e e . .
        . e e b b b b b b b b b e e .
        e e b b c c c c c c c b b e e
        e b b c e e e e e e e c b c e
        e b c e a a a a a a a e b c e
        e b c e a a a a a a a e b c e
        e b c e a a a a a a a e b c e
        e b c e a a a a a a a e b c e
        e b c e a a a a a a a e b c e
        e b c e a a a a a a a e b c e
        e b c e a a a a a a a e b c e
        e b b c e e e e e e e b b c e
        e e b b b b b b b b b b c e e
        . e e c c c c c c c c c e e .
        . . e e e e e e e e e e e . .
    `;

    export const scrollbarDown = img`
        f f f f f f f f f
        f c c c c c c c f
        f c f f f f f c f
        f c f f f f f c f
        f c c f f f c c f
        f c c f f f c c f
        f c c c f c c c f
        f d d d d d d d f
        f f f f f f f f f
    `;

    export const scrollbarUp = img`
        f f f f f f f f f
        f c c c c c c c f
        f c c c f c c c f
        f c c f f f c c f
        f c c f f f c c f
        f c f f f f f c f
        f c f f f f f c f
        f d d d d d d d f
        f f f f f f f f f
    `;

    export const homeIcon = img`
        . . . . . a a . a . . .
        . . . . a 2 2 a c a . .
        . . . a 2 2 2 2 c a . .
        . . a 2 2 2 2 2 2 a . .
        . a 2 2 2 2 2 2 2 2 a .
        a 2 2 2 2 2 2 2 2 2 2 a
        . d b b b b b b b b d .
        . d b 9 b b b b 9 b d .
        . d b 9 b a a b 9 b d .
        . d b b b a 4 b b b d .
        . d b b b a a b b b d .
        . . d d d d d d d d . .
    `;

    export const homeIconHover = img`
        . . . . . . 4 4 . 4 . . . .
        . . . . . 4 a a 4 a 4 . . .
        . . . . 4 a 2 2 a c a 4 . .
        . . . 4 a 2 2 2 2 c a 4 . .
        . . 4 a 2 2 2 2 2 2 a 4 . .
        . 4 a 2 2 2 2 2 2 2 2 a 4 .
        4 a 2 2 2 2 2 2 2 2 2 2 a 4
        . 4 d b b b b b b b b d 4 .
        . 4 d b 9 b b b b 9 b d 4 .
        . 4 d b 9 b a a b 9 b d 4 .
        . 4 d b b b a 4 b b b d 4 .
        . 4 d b b b a a b b b d 4 .
        . . 4 d d d d d d d d 4 . .
        . . . 4 4 4 4 4 4 4 4 . . .
    `;

    export const padlock = img`
        .....fffffff.....
        ...ffdccccccff...
        ..fdccccccccccf..
        .fdccccfffdccccf.
        .fdcccf...fdcccf.
        .fdccf.....fdccf.
        .fdccf.....fdccf.
        .fdccf.....fdccf.
        .fdccf.....fdccf.
        .fdccf.....fdccf.
        .fdccf.....fdccf.
        fffffffffffffffff
        fedcccccccccccdef
        fedcccccccccccdef
        fedccccfffccccdef
        fedcccfffffcccdef
        fedcccfffffcccdef
        fedcccfffffcccdef
        fedccccfffccccdef
        fedccccfffccccdef
        fedcccccccccccdef
        fedcccccccccccdef
        fffffffffffffffff
    `;

    export const cloudLayer0 = img`
        bbbbbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbbbbbbbbbb....bbbbbbbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....bbbbb..bbbbbbbbbbbbbbbbbb......
        bbbbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....bbbbb..bbbbbbbbbbbbbbbbbb......bbbbbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...........bbbbbbbbbbbbbb..........
        bbbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...........bbbbbbbbbbbbbb.............bbbbbbbbb..bbbbbbbbbbbbbbbbbbbbbb.bbbbbbbbb............bbbb.bbbbbbbbb.........
        .bbbbbbbbb..bbbbbbbbbbbbbbbbbbbbbb.bbbbbbbbb............bbbb.bbbbbbbbb.............bbbbb.....bbbbbb.bbbbbbbbbbbbbbbb...bbbbb..................bbbbbbbbb.........
        ..bbbbb.....bbbbbb.bbbbbbbbbbbbbbbb...bbbbb..................bbbbbbbbb............bbbbb.......bbbb.bbbbbbbbbbbbbbbbbb..bbbbb................bbbbbb.bbb..........
        .bbbbb.......bbbb.bbbbbbbbbbbbbbbbbb..bbbbb................bbbbbb.bbb.............bbbbb...........bbbbbbbbbbbbbbbbbbb...bb..................bbbbbb..............
        .bbbbb...........bbbbbbbbbbbbbbbbbbb...bb..................bbbbbb..................bbb...........bbbbbbbbbbbbbbbbbbbb........................bbbb...............
        ..bbb...........bbbbbbbbbbbbbbbbbbbb........................bbbb.................................bbbbbbbbbbbbbbbbbbb............................................
        ................bbbbbbbbbbbbbbbbbbb...............................................................bbbbbbbbbbbbbbbb..............................................
        .................bbbbbbbbbbbbbbbb..................................................................bbbbbbbbb.bbbbb..............................................
        ..................bbbbbbbbb.bbbbb.....................................................................bbbbbb..bb................................................
        .....................bbbbbb..bb.......................................................................bbbbbb....................................................
        .....................bbbbbb............................................................................bbbb.....................................................
        ......................bbbb......................................................................................................................................
    `;

    export const cloudLayer1 = img`
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        ccccccccccccccc.cccccccc.cccccccccccccccccccccccccccccc.cccccccc.cccccccccccccccccccccccccccccc.cccccccc.cccccccccccccccccccccccccccccc.cccccccc.ccccccccccccccc
        c.cccccccccccc...cccccc.ccccccccccccccccc.cccccccccccc...cccccc.ccccccccccccccccc.cccccccccccc...cccccc.ccccccccccccccccc.cccccccccccc...cccccc.cccccccccccccccc
        c..cccccccccc......cc...ccccccccccccccccc..cccccccccc......cc...ccccccccccccccccc..cccccccccc......cc...ccccccccccccccccc..cccccccccc......cc...cccccccccccccccc
        c....cccccc............cccccccccccccccccc....cccccc............cccccccccccccccccc....cccccc............cccccccccccccccccc....cccccc............ccccccccccccccccc
        .......................ccccccccccc.ccccc.......................ccccccccccc.ccccc.......................ccccccccccc.ccccc.......................ccccccccccc.ccccc
        .......................ccccccccccc..ccc........................ccccccccccc..ccc........................ccccccccccc..ccc........................ccccccccccc..ccc.
        ........................ccccccccc...............................ccccccccc...............................ccccccccc...............................ccccccccc.......
        .........................ccccccc.................................ccccccc.................................ccccccc.................................ccccccc........
        ...........................ccc.....................................ccc.....................................ccc.....................................ccc..........
    `;

    export const cloudLayer2 = img`
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.ddddddddddddddddddddddddddddddddddd
        ddddddddddddddddddddddddddddddddddddddddddd.dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.dddddddddddddddddddddddddddddd...dd
        ddddddddddddddddddddddddddddddddddddddddddd.dddddddddddddddddddddddddddddd...ddddddddddddddddd.dddddddddddddddddddddddddddddd.ddddddddddddddddddddddddddddd....d
        ddddddddddddd.dddddddddddddddddddddddddddddd.ddddddddddddddddddddddddddddd....ddddddddddddddd.ddddddddddddddddddddddddddddddd....ddddd..dddddddddddddddddd......
        dddddddddddd.ddddddddddddddddddddddddddddddd....ddddd..dddddddddddddddddd......ddddddddddddd.dddddddddddddddddddddddddddddddd...........dddddddddddddd..........
        ddddddddddd.dddddddddddddddddddddddddddddddd...........dddddddddddddd.............ddddddddd..dddddddddddddddddddddd.ddddddddd............dddd.ddddddddd.........
        .ddddddddd..dddddddddddddddddddddd.ddddddddd............dddd.ddddddddd.............ddddd.....dddddd.dddddddddddddddd...ddddd..................ddddddddd.........
        ..ddddd.....dddddd.dddddddddddddddd...ddddd..................ddddddddd............ddddd.......dddd.dddddddddddddddddd..ddddd................dddddd.ddd..........
        .ddddd.......dddd.dddddddddddddddddd..ddddd................dddddd.ddd.............ddddd...........ddddddddddddddddddd...dd..................dddddd..............
        .ddddd...........ddddddddddddddddddd...dd..................dddddd..................ddd...........dddddddddddddddddddd........................dddd...............
        ..ddd...........dddddddddddddddddddd........................dddd.................................ddddddddddddddddddd............................................
        ................ddddddddddddddddddd...............................................................dddddddddddddddd..............................................
        .................dddddddddddddddd..................................................................ddddddddd.ddddd..............................................
        ..................ddddddddd.ddddd.....................................................................dddddd..dd................................................
        .....................dddddd..dd.......................................................................dddddd....................................................
        .....................dddddd............................................................................dddd.....................................................
        ......................dddd......................................................................................................................................
    `;

    export const cloudLayer3 = img`
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
        dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.ddddddddddddddddddddddddddddddddddd
        ddddddddddddddddddddddddddddddddddddddddddd.dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.dddddddddddddddddddddddddddddd...dd
        ddddddddddddddddddddddddddddddddddddddddddd.dddddddddddddddddddddddddddddd...ddddddddddddddddd.dddddddddddddddddddddddddddddd.ddddddddddddddddddddddddddddd....d
        ddddddddddddd.dddddddddddddddddddddddddddddd.ddddddddddddddddddddddddddddd....ddddddddddddddd.ddddddddddddddddddddddddddddddd....ddddd..dddddddddddddddddd......
        dddddddddddd.ddddddddddddddddddddddddddddddd....ddddd..dddddddddddddddddd......ddddddddddddd.dddddddddddddddddddddddddddddddd...........dddddddddddddd..........
        ddddddddddd.dddddddddddddddddddddddddddddddd...........dddddddddddddd.............ddddddddd..dddddddddddddddddddddd.ddddddddd............dddd.ddddddddd.........
        .ddddddddd..dddddddddddddddddddddd.ddddddddd............dddd.ddddddddd.............ddddd.....dddddd.dddddddddddddddd...ddddd..................ddddddddd.........
        ..ddddd.....dddddd.dddddddddddddddd...ddddd..................ddddddddd............ddddd.......dddd.dddddddddddddddddd..ddddd................dddddd.ddd..........
        .ddddd.......dddd.dddddddddddddddddd..ddddd................dddddd.ddd.............ddddd...........ddddddddddddddddddd...dd..................dddddd..............
        .ddddd...........ddddddddddddddddddd...dd..................dddddd..................ddd...........dddddddddddddddddddd........................dddd...............
        ..ddd...........dddddddddddddddddddd........................dddd.................................ddddddddddddddddddd............................................
        ................ddddddddddddddddddd...............................................................dddddddddddddddd..............................................
        .................dddddddddddddddd..................................................................ddddddddd.ddddd..............................................
        ..................ddddddddd.ddddd.....................................................................dddddd..dd................................................
        .....................dddddd..dd.......................................................................dddddd....................................................
        .....................dddddd............................................................................dddd.....................................................
        ......................dddd......................................................................................................................................
    `;

    export const lightningFrames = [
        img`
        ...........1....................
        ............1...................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        .................1..............
        ..................1.............
        ...................1............
        ....................1...........
        .....................1..........
        ......................1.........
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, img`
        ...........1....................
        ............1...................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        .................1..............
        ..................1.............
        ...................1............
        ....................1...........
        .....................1..........
        ......................1.........
        .......................1........
        ........................1.......
        ........................1.......
        .......................1........
        ......................1.........
        .....................1..........
        ....................1...........
        ...................1............
        ..................1.............
        .................1..............
        ................1...............
        ...............1................
        ..............1.................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, img`
        ...........1....................
        ............1...................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        .................1..............
        ..................1.............
        ...................1............
        ....................1...........
        .....................1..........
        ......................1.........
        .......................1........
        ........................1.......
        ........................1.......
        .......................1........
        ......................1.........
        .....................1..........
        ....................1...........
        ...................1............
        ..................1.............
        .................1..............
        ................1...............
        ...............1................
        ..............1.................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        ...............1.11.............
        ...............1...1............
        ...............1....1...........
        ..............1......1..........
        ..............1.......11........
        ..............1......1..1.......
        .............1.......1...1......
        .............1......1.....1.....
        ............1.......1...........
        ............1...................
        ...........1....................
        ...........1....................
        ..........1.....................
        ..........1.....................
        .........1......................
        ........1.......................
        ........1.......................
        .......1........................
        .......1........................
        ......1.........................
        ......1.........................
        .......1........................
        .......1........................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, img`
        ...........1....................
        ............1...................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        .................1..............
        ..................1.............
        ...................1............
        ....................1...........
        .....................1..........
        ......................1.........
        .......................1........
        ........................1.......
        ........................1.......
        .......................1........
        ......................1.........
        .....................1..........
        ....................1...........
        ...................1............
        ..................1.............
        .................1..............
        ................1...............
        ...............1................
        ..............1.................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        ...............1.11.............
        ...............1...1............
        ...............1....1...........
        ..............1......1..........
        ..............1.......11........
        ..............1......1..1.......
        .............1.......1...1......
        .............1......1.....1.....
        ............1.......1...........
        ............1...................
        ...........1....................
        ...........1....................
        ..........1.....................
        ..........1.....................
        .........1......................
        ........1.......................
        ........1.......................
        .......1........................
        .......1........................
        ......1.........................
        ......1.........................
        .......1........................
        .......1........................
        .......1........................
        ........1.......................
        ........1.......................
        .........1......................
        .........1......................
        .........1......................
        ..........1.....................
        ..........1.....................
        ..........1.....................
        ...........1....................
        ...........1....................
        ............1...................
        ............1...................
        ............1...................
        .............1..................
        .............1..................
        ..............1.................
        ..............1.................
        ..............1.................
        ...............1................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, img`
        ...........1....................
        ............1...................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        .................1..............
        ..................1.............
        ...................1............
        ....................1...........
        .....................1..........
        ......................1.........
        .......................1........
        ........................1.......
        ........................1.......
        .......................1........
        ......................1.........
        .....................1..........
        ....................1...........
        ...................1............
        ..................1.............
        .................1..............
        ................1...............
        ...............1................
        ..............1.................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        ...............1.11.............
        ...............1...1............
        ...............1....1...........
        ..............1......1..........
        ..............1.......11........
        ..............1......1..1.......
        .............1.......1...1......
        .............1......1.....1.....
        ............1.......1...........
        ............1...................
        ...........1....................
        ...........1....................
        ..........1.....................
        ..........1.....................
        .........1......................
        ........1.......................
        ........1.......................
        .......1........................
        .......1........................
        ......1.........................
        ......1.........................
        .......1........................
        .......1........................
        .......1........................
        ........1.......................
        ........1.......................
        .........1......................
        .........1......................
        .........1......................
        ..........1.....................
        ..........1.....................
        ..........1.....................
        ...........1....................
        ...........1....................
        ............1...................
        ............1...................
        ............1...................
        .............1..................
        .............1..................
        ..............1.................
        ..............1.................
        ..............1.................
        ...............1................
        ...............1................
        ...............1................
        ................1...............
        ................1...............
        .................1..............
        .................1..............
        .................1..............
        ..................1.............
        ..................1.............
        .................1.1............
        .................1.1............
        ................1...1...........
        ...............1.....1..........
        ..............1......1..........
        .............1........1.........
        .............1.........1........
        ............1..........1........
        ...........1............1.......
        `, img`
        ...........1....................
        ............1...................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        .................1..............
        ..................1.............
        ...................1............
        ....................1...........
        .....................1..........
        ......................1.........
        .......................1........
        ........................1.......
        ........................1.......
        .......................1........
        ......................1.........
        .....................1..........
        ....................1...........
        ...................1............
        ..................1.............
        .................1..............
        ................1...............
        ...............1................
        ..............1.................
        .............1..................
        ..............1.................
        ...............1................
        ................1...............
        ...............1.11.............
        ...............1...1............
        ...............1....1...........
        ..............1......1..........
        ..............1.......11........
        ..............1......1..1.......
        .............1.......1...1......
        .............1......1.....1.....
        ............1.......1...........
        ............1...................
        ...........1....................
        ...........1....................
        ..........1.....................
        ..........1.....................
        .........1......................
        ........1.......................
        ........1.......................
        .......1........................
        .......1........................
        ......1.........................
        ......1.........................
        .......1........................
        .......1........................
        .......1........................
        ........1.......................
        ........1.......................
        .........1......................
        .........1......................
        .........1......................
        ..........1.....................
        ..........1.....................
        ..........1.....................
        ...........1....................
        ...........1....................
        ............1...................
        ............1...................
        ............1...................
        .............1..................
        .............1..................
        ..............1.................
        ..............1.................
        ..............1.................
        ...............1................
        ...............1................
        ...............1................
        ................1...............
        ................1...............
        .................1..............
        .................1..............
        .................1..............
        ..................1.............
        ..................1.............
        .................1.1............
        .................1.1............
        ................1...1...........
        ...............1.....1..........
        ..............1......1..........
        .............1........1.........
        .............1.........1........
        ............1..........1........
        ...........1............1.......
        `, img`
        ...........1.....111............
        ............1....1..............
        .............1..1...............
        ..............1.1...............
        ...............1................
        ..............111...............
        ..............1..1..............
        .............11...1.............
        .............1.....1............
        ............11......1...........
        ............1........1..........
        ...........11.........1.........
        ...........1...........1........
        ..........11............1.......
        .........11.............1.......
        .........11............1........
        ........11............1.........
        ........11...........1..........
        .......11...........1...........
        .......11..........1............
        .......11.........1.............
        .......11........1..............
        .......11.......1...............
        ........11.....1................
        ........11....1.................
        ........11...1..................
        .........11...1.................
        .........111...1................
        .........111....1...............
        ..........111..1.11.............
        ..........111..1...1............
        ...........11..1....1...........
        ...........1111......1..........
        ...........1111.......11........
        ............111......1..1.......
        ............111......1...1......
        ............111.....1.....1.....
        ............1111....1...........
        ............1111................
        ...........1.1111...............
        ...........1..111...............
        ..........1...111...............
        ..........1...1111..............
        .........1.....111..............
        ........1......1111.............
        ........1.......111.............
        .......1........1111............
        .......1.........111............
        ......1...........11............
        ......1............11...........
        .......1............1...........
        .......1............1...........
        .......1............11..........
        ........1...........11..........
        ........1...........11..........
        .........1.........111..........
        .........1.........111..........
        .........1........1111..........
        ..........1.......111...........
        ..........1.......111...........
        ..........1......111............
        ...........1.....111............
        ...........1....111.............
        ............1...111.............
        ............1..111..............
        ............1..111..............
        .............1111...............
        .............1111...............
        ..............11................
        .............111................
        .............11.................
        ............11.1................
        ............11.1................
        ...........111.1................
        ...........11...1...............
        ..........111...1...............
        ............1....1..............
        ............11...1..............
        ............11...1..............
        .............11...1.............
        .............11...1.............
        ..............11.1.1............
        ..............11.1.1............
        ..............111...1...........
        ...............11....1..........
        ..............1111...1..........
        .............1..11..1.1.........
        .............1..111..1.1........
        ............1.1..11..1.11.......
        ...........1...1.111...11.......
        `, img`
        .................bbb............
        .................b..............
        ................b...............
        ................b...............
        ...............b................
        ..............bb................
        ..............b.................
        .............bb.................
        .............b..................
        ............bb..................
        ............b...................
        ...........bb...................
        ...........b....................
        ..........bb....................
        .........bb.....................
        .........bb.....................
        ........bb......................
        ........bb......................
        .......bb.......................
        .......bb.......................
        .......bb.......................
        .......bb.......................
        .......bb.......................
        ........bb......................
        ........bb......................
        ........bb......................
        .........bb.....................
        .........bbb....................
        .........bbb....................
        ..........bbb...................
        ..........bbb...................
        ...........bb...................
        ...........bbb..................
        ...........bbb..................
        ............bbb.................
        ............bbb.................
        ............bbb.................
        ............bbbb................
        ............bbbb................
        .............bbbb...............
        ..............bbb...............
        ..............bbb...............
        ..............bbbb..............
        ...............bbb..............
        ...............bbbb.............
        ................bbb.............
        ................bbbb............
        .................bbb............
        ..................bb............
        ...................bb...........
        ....................b...........
        ....................b...........
        ....................bb..........
        ....................bb..........
        ....................bb..........
        ...................bbb..........
        ...................bbb..........
        ..................bbbb..........
        ..................bbb...........
        ..................bbb...........
        .................bbb............
        .................bbb............
        ................bbb.............
        ................bbb.............
        ...............bbb..............
        ...............bbb..............
        ..............bbb...............
        ..............bbb...............
        ..............bb................
        .............bbb................
        .............bb.................
        ............bb..................
        ............bb..................
        ...........bbb..................
        ...........bb...................
        ..........bbb...................
        ..........bbb...................
        ............bb..................
        ............bb..................
        .............bb.................
        .............bb.................
        ..............bb................
        ..............bb................
        ..............bbb...............
        ...............bb...............
        ...............bbb..............
        ..............bbbbbbb...........
        ............bbbbbbbbbbbb........
        ...........bbbbbbbbbbbbbb.......
        ...........bbbbbbbbbbbbbb.......
        `, img`
        .................bbb............
        .................b..............
        ................b...............
        ................b...............
        ...............b................
        ..............bb................
        ..............b.................
        .............bb.................
        .............b..................
        ............bb..................
        ............b...................
        ...........bb...................
        ...........b....................
        ..........bb....................
        .........bb.....................
        .........bb.....................
        ........bb......................
        ........bb......................
        .......bb.......................
        .......bb.......................
        .......bb.......................
        .......bb.......................
        .......bb.......................
        ........bb......................
        ........bb......................
        ........bb......................
        .........bb.....................
        .........bbb....................
        .........bbb....................
        ..........bbb...................
        ..........bbb...................
        ...........bb...................
        ...........bbb..................
        ...........bbb..................
        ............bbb.................
        ............bbb.................
        ............bbb.................
        ............bbbb................
        ............bbbb................
        .............bbbb...............
        ..............bbb...............
        ..............bbb...............
        ..............bbbb..............
        ...............bbb..............
        ...............bbbb.............
        ................bbb.............
        ................bbbb............
        .................bbb............
        ..................bb............
        ...................bb...........
        ....................b...........
        ....................b...........
        ....................bb..........
        ....................bb..........
        ....................bb..........
        ...................bbb..........
        ...................bbb..........
        ..................bbbb..........
        ..................bbb...........
        ..................bbb...........
        .................bbb............
        .................bbb............
        ................bbb.............
        ................bbb.............
        ...............bbb..............
        ...............bbb..............
        ..............bbb...............
        ..............bbb...............
        ..............bb................
        .............bbb................
        .............bb.................
        ............bb..................
        ............bb..................
        ...........bbb..................
        ...........bb...................
        ..........bbb...................
        ...........bb...................
        ............bb..................
        ............bb..................
        .............bb.................
        .............bb.....b...........
        ..............bb....bb..........
        ..............bb..bbbbbb........
        .........bb.bbbbbbbbbbbb........
        .........bbbbbbbbbbbbbbb........
        ..........bbbbbbbbbbbbbbbbb.....
        ...........bbbbbbbbbbbbbbbb.....
        .........bbbbbbbbbbbbbbbbb......
        .........bbbbbbbbbbbbbbbb.......
        ..........bbbbbbbbbbbbbbb.b.....
        `, img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        .......b........................
        ......b.........................
        ......b.........................
        .......b........................
        .......b........................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ..................bb............
        ...................bb...........
        ....................b...........
        ....................b...........
        ....................b...........
        ....................b...........
        ....................b...........
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ............bb..................
        ...........bbb..................
        ...........b....................
        ..........bb....................
        ..........bb....................
        ...........b....................
        ............b...................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ..........................b.....
        `, img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        .......b........................
        ................................
        ....b...........................
        ................................
        ....b...........................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ....................b...........
        .....................b..........
        ................................
        ......................b.........
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ..........b.....................
        .........b......................
        ................................
        ................................
        ................................
        .........b......................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ..........................b.....
        `
    ];
}